name: llama-russian

services:
    app:
        build: .
        volumes:
            - .:/app:z
            - /home/serhii/models/sambanovasystems-SambaLingo-Russian-Base-GGUF-smashed:/model:z
        tty: true
        restart: unless-stopped
